export enum TipoEventoEnum {
  SHOW ='SHOW',
  DJ ='DJ',
  FESTA_TEMATICA ='FESTA_TEMATICA',
  KARAOKE ='KARAOKE',
  STAND_UP ='STAND_UP',
  PROMOCAO ='PROMOCAO',
  EVENTO_GASTRONOMICO ='EVENTO_GASTRONOMICO',
  EVENTO_PRIVADO ='EVENTO_PRIVADO',
  LANCAMENTO_CARDAPIO ='LANCAMENTO_CARDAPIO',
  HAPPY_HOUR ='HAPPY_HOUR',
  OPEN_BAR ='OPEN_BAR',
  FEIRA_CULTURAL ='FEIRA_CULTURAL',
  OUTRO='OUTRO'
}
