export enum TipoEstabelecimentoEnum {
  RESTAURANTE = 'RESTAURANTE',
  LANCHONETE = 'LANCHONETE',
  CAFETERIA = 'CAFETERIA',
  BAR = 'BAR',
  PUB = 'PUB',
  BOATE = 'BOATE',
  SORVETERIA = 'SORVETERIA',
  DOCERIA = 'DOCERIA',
  CONFEITARIA = 'CONFEITARIA',
  FAST_FOOD = 'FAST_FOOD',
  CHOPERIA = 'CHOPERIA',
  BUFFET = 'BUFFET',
  CASA_DE_SHOWS = 'CASA_DE_SHOWS',
  OUTRO = 'OUTRO'
}
