spring:
  application:
    name: estabelecimento
  datasource:
    url: jdbc:postgresql://localhost:5437/estabelecimento
    username: estabelecimento
    password: estabelecimento
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update